name: EmojiVoto
vars:
  namespace: {}
services:
  web:
    type: Application
    namespace: $(#ref.vars.namespace)
    settings:
      replicas: 1
      advanced:
        labels:
          app.kubernetes.io/name: web
          app.kubernetes.io/part-of: emojivoto
          app.kubernetes.io/version: v11
      containers:
      - env:
        - name: WEB_PORT
          value: "8080"
        - name: EMOJISVC_HOST
          value: emoji-svc.emojivoto:8080
        - name: VOTINGSVC_HOST
          value: voting-svc.emojivoto:8080
        - name: INDEX_BUNDLE
          value: dist/index_bundle.js
        image: docker.l5d.io/buoyantio/emojivoto-web:v11
        name: web-svc
        ports:
        - containerPort: 8080
          name: http
  voting:
    type: Application
    namespace: $(#ref.vars.namespace)
    settings:
      advanced:
        labels:
          app.kubernetes.io/name: voting
          app.kubernetes.io/part-of: emojivoto
          app.kubernetes.io/version: v11
      replicas: 1
      containers:
      - env:
        - name: GRPC_PORT
          value: "8080"
        - name: PROM_PORT
          value: "8801"
        image: docker.l5d.io/buoyantio/emojivoto-voting-svc:v11
        name: voting-svc
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 8801
          name: prom
  emojivoto:
    type: Application
    namespace: $(#ref.vars.namespace)
    settings:
      replicas: 1
      containers:
      - env:
        - name: GRPC_PORT
          value: "8080"
        - name: PROM_PORT
          value: "8801"
        image: docker.l5d.io/buoyantio/emojivoto-emoji-svc:v11
        name: emoji-svc
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 8801
          name: prom
      advanced:
        labels:
          app: emoji-svc
          version: v11
