name: EmojiVoto
services:
  emojins:
    type: Namespace.K8s
    settings: 
      name: emojivoto
  votebot:
    type: Deployment.K8s
    namespace: emojivoto
    dependsOn:
      - emojins
    settings:
      replicas: 1
      selector:
        matchLabels:
          app: vote-bot
          version: v11
      template:
        metadata:
          labels:
            app: vote-bot
            version: v11
        spec:
          containers:
          - command:
            - emojivoto-vote-bot
            env:
            - name: WEB_HOST
              value: web-svc.emojivoto:80
            image: docker.l5d.io/buoyantio/emojivoto-web:v11
            name: vote-bot
            resources:
              requests:
                cpu: 10m
  web:
    type: Application
    namespace: emojivoto
    dependsOn:
      - emojins
    settings:
      replicas: 1
      advanced:
        labels:
          app.kubernetes.io/name: web
          app.kubernetes.io/part-of: emojivoto
          app.kubernetes.io/version: v11
      containers:
      - env:
        - name: WEB_PORT
          value: "8080"
        - name: EMOJISVC_HOST
          value: emoji-svc.emojivoto:8080
        - name: VOTINGSVC_HOST
          value: voting-svc.emojivoto:8080
        - name: INDEX_BUNDLE
          value: dist/index_bundle.js
        image: docker.l5d.io/buoyantio/emojivoto-web:v11
        name: web-svc
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 100m
  voting:
    type: Application
    namespace: emojivoto
    dependsOn:
      - emojins
    settings:
      advanced:
        labels:
          app.kubernetes.io/name: voting
          app.kubernetes.io/part-of: emojivoto
          app.kubernetes.io/version: v11
      replicas: 1
      containers:
      - env:
        - name: GRPC_PORT
          value: "8080"
        - name: PROM_PORT
          value: "8801"
        image: docker.l5d.io/buoyantio/emojivoto-voting-svc:v11
        name: voting-svc
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 8801
          name: prom
        resources:
          requests:
            cpu: 100m
  emojivoto:
    type: Application
    namespace: emojivoto
    dependsOn:
      - emojins
    settings:
      replicas: 1
      containers:
      - env:
        - name: GRPC_PORT
          value: "8080"
        - name: PROM_PORT
          value: "8801"
        image: docker.l5d.io/buoyantio/emojivoto-emoji-svc:v11
        name: emoji-svc
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 8801
          name: prom
        resources:
          requests:
            cpu: 100m
      advanced:
        labels:
          app: emoji-svc
          version: v11
