name: Test Istio Adapter

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:
    branches:
      - main
jobs:
  SetPatterfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Change service mesh version in patternfile
        run: | 
           
           yq e -i '.services.istio.settings.version="1.4.4"' ./.github/install/deploy.yaml 
           cat ./.github/install/deploy.yaml
      - name: Uploading file
        uses: actions/upload-artifact@v2
        with:
          name: patternfile
          path: ./.github/install/deploy.yaml 

  TestIstio:
    needs: SetPatterfile
    uses: meshery/meshery/.github/workflows/testadapters.yaml@master
    with:
      expected_pods: grafana-core,jaeger,prometheus-core,traefik-mesh-controller,traefik-mesh-proxy
      expected_pods_namespaces: traefik,traefik,traefik,traefik,traefik
      deployment_url: https://raw.githubusercontent.com/meshery/meshery/master/install/deployment_yamls/k8s/meshery-traefik-mesh-deployment.yaml
      service_url: https://raw.githubusercontent.com/meshery/meshery/master/install/deployment_yamls/k8s/meshery-traefik-mesh-service.yaml
      adapter_name: traefik-mesh
      patternfile_name: deploy.yaml
    secrets:
      token: ${{ secrets.PROVIDER_TOKEN }}