name: Test NginxSM Adapter

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:
    branches:
      - "*"
jobs:
  SetPatternfile:
    runs-on: ubuntu-latest
    outputs:
      sm_version: ${{ steps.gettag.outputs.release }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Get latest release tag
        id: gettag
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: istio/istio
          excludes: prerelease, draft, edge 
      - name: Change service mesh version in patternfile
        run: | 
           
           yq e -i '.services.istio.settings.version="${{ steps.gettag.outputs.release }}"' ./.github/install/deploy.yaml 
           cat ./.github/install/deploy.yaml
      - name: Uploading file
        uses: actions/upload-artifact@v2
        with:
          name: patternfile
          path: ./.github/install/deploy.yaml 

  TestLinkerd:
    needs: SetPatternfile
    uses: Revolyssup/test-workflows/.github/workflows/general.yaml@main
    with:
      expected_pods: istiod,istio-egressgateway,istio-ingressgateway
      expected_pods_namespaces: istio-system,istio-system,istio-system
      deployment_url: https://raw.githubusercontent.com/meshery/meshery/master/install/deployment_yamls/k8s/meshery-istio-deployment.yaml
      service_url: https://raw.githubusercontent.com/meshery/meshery/master/install/deployment_yamls/k8s/meshery-istio-service.yaml
      adapter_name: istio
      patternfile_name: deploy.yaml
      provider: Local
      k8s_version: v1.20.1
      sm_version: ${{ needs.SetPatternfile.outputs.sm_version }}
    secrets:
      token: ${{ secrets.PROVIDER_TOKEN }} 
  
  UpdateDocs:
    if: always()
    needs: TestLinkerd
    runs-on: ubuntu-latest
    steps:
      - name: DownloadJSON
        uses: actions/download-artifact@v2
        with:
          name: data.json
      - name: echo results
        run: cat ./data.json
